### ISSUE TITLE
"Don't add torrent's name to path" option

### ISSUE THREAD

**Issue by JohnFlowerful** [gtorrent/gtorrent-core#61]
Requesting a feature like that of rutorrent/rtorrent:
![rutorrent screen](http://imageshack.com/a/img537/371/Va4Pdr.png)

This would be useful for cross-seeding torrents. For example: 
You have two torrent for 'lots of files'; _torrent a_ and _torrent b_. Both torrents contain the same content. However, _torrent a_ wants to create a directory called 'lots.of.files' while _torrent b_ wants to create the directory 'lots_of_files'. To cross-seed in this situation, you would need to edit either _torrent a's_ or _torrent b's_ torrent file to match the directories.
With the "Don't add torrent's name to path" option, this would not be a problem. Users would not need to edit torrent files which in turn means cross-seeding with trackers that check torrent hashes would be possible.

**Comment by bobbintb** [comment]
I know it's an old topic but since it's still open, I get what he's saying. It's been a feature I've been looking for forever until I found it in rtorrent. It's essential for cross seeding. Say you download a torrent from one tracker and it downloads "mymovie1.mov", ""mymovie2.mov", and "mymovie3.mov". Now you want to cross seed that on a different tracker but the person that uploaded it to that tracker decided to put all those files in a folder "my_movies" before creating the torrent. Even though those files are the same files, they are in a folder so if you try to cross seed the data the files will not be found and will not pass a hash check because the folder structure is different.

**Comment by IGI-111** [comment]
That's a protocol limitation, I'm not aware of a way to seed by individual file hash on bittorent, and even less so to resolve individual files through the DHT.

[IPFS](https://ipfs.io/) exists for that very reason though, and it even works on chunks, not just files.

**Comment by benwaffle** [comment]
lol gtorrent

**Comment by bobbintb** [comment]
I dunno, just clarifying the issue. I do know rtorrent has that feature and I use it all the time so there obviously is a way.

**Comment by nyanpasu** [comment]
I think it's possible to modify the file mappings of a torrent file.

libtorrent-rasterbar appears to [support](http://www.libtorrent.org/reference-Core.html#remap-files) it.

**Comment by IGI-111** [comment]
I guess you can take advantage of that to seed your files with and without a top level folder, but it's a pretty ugly hack. Would definitely be nice if you could have individual hashing for every file.

But at least it's a solution for that problem indeed.

**Comment by nyanpasu** [comment]
What is ugly about it?

You can choose which pieces you want to seed, but that's a different feature.

Files are just mappings to pieces.

**Comment by IGI-111** [comment]
Essentially, at that point you're just seeding two separate torrent hashes linked to the same chunks of data. You just created a whole other metadata set just to convey a lack of top level folder.

Maybe it's just me, but that's damn ugly.

If you really wanted to avoid tracker misses, you'd also want to seed for torrents that aren't yours, but contain the same files (and with the number of release teams that just copy shit from the scene that does happen quite a lot) but to do that you'd have to create yet another amount of metadata.

The central problem here is that bittorrent doesn't do file level hashing.

So yeah what you propose should work and it should work well for this precise issue, but it's very much a workaround for protocol limitations.

<sub>And now I realize I'm ranting.</sub>

**Comment by bobbintb** [comment]
Just a note, it might be rutorrent that does this and not rtorrent.

**Comment by Merlincool** [comment]
This is very important feature and could help if there is a cli way to do it.

**Comment by nyanpasu** [comment]
Well, looking back at it, I change withdraw my opinion on it. @IGI-111 and @fuyukaidesu was right, it's pretty hacky.

Fix your torrents manually. You can also achieve the requested functionality using hardlinks. It's not a concern of your bittorrent client to handle that use case, although simple. Where do we draw the line? What if two torrents have the same set of files, but have a totally directory layout? Do we account for that too? If not, why this but not that?

Not gonna support it :^)
